# Generated by Django 4.1.1 on 2022-09-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='id_rider',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='rideevent',
            old_name='id_ride',
            new_name='ride',
        ),
    ]
