# Generated by Django 4.1.1 on 2022-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('R', 'Rider'), ('D', 'Driver')], max_length=1),
        ),
    ]
